[package]
name = "escape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.1"
macroquad-tiled = "0.2.0"
once_cell = "1.18.0"
